// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opts.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	opts.proto

It has these top-level messages:
	MyMessage
	RequestType
	ResponseType
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
// import google_protobuf "google/protobuf"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type MyEnum int32

const (
	MyEnum_FOO MyEnum = 1
	MyEnum_BAR MyEnum = 2
)

var MyEnum_name = map[int32]string{
	1: "FOO",
	2: "BAR",
}
var MyEnum_value = map[string]int32{
	"FOO": 1,
	"BAR": 2,
}

func (x MyEnum) Enum() *MyEnum {
	p := new(MyEnum)
	*p = x
	return p
}
func (x MyEnum) String() string {
	return proto1.EnumName(MyEnum_name, int32(x))
}
func (x *MyEnum) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(MyEnum_value, data, "MyEnum")
	if err != nil {
		return err
	}
	*x = MyEnum(value)
	return nil
}
func (MyEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MyMessage struct {
	Foo              *int32  `protobuf:"varint,1,opt,name=foo" json:"foo,omitempty"`
	Bar              *string `protobuf:"bytes,2,opt,name=bar" json:"bar,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MyMessage) Reset()                    { *m = MyMessage{} }
func (m *MyMessage) String() string            { return proto1.CompactTextString(m) }
func (*MyMessage) ProtoMessage()               {}
func (*MyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MyMessage) GetFoo() int32 {
	if m != nil && m.Foo != nil {
		return *m.Foo
	}
	return 0
}

func (m *MyMessage) GetBar() string {
	if m != nil && m.Bar != nil {
		return *m.Bar
	}
	return ""
}

type RequestType struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestType) Reset()                    { *m = RequestType{} }
func (m *RequestType) String() string            { return proto1.CompactTextString(m) }
func (*RequestType) ProtoMessage()               {}
func (*RequestType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ResponseType struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResponseType) Reset()                    { *m = ResponseType{} }
func (m *ResponseType) String() string            { return proto1.CompactTextString(m) }
func (*ResponseType) ProtoMessage()               {}
func (*ResponseType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

var E_MyFileOption = &proto1.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50000,
	Name:          "mypb.my_file_option",
	Tag:           "bytes,50000,opt,name=my_file_option,json=myFileOption",
	Filename:      "opts.proto",
}

var E_MyMessageOption = &proto1.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         50001,
	Name:          "mypb.my_message_option",
	Tag:           "varint,50001,opt,name=my_message_option,json=myMessageOption",
	Filename:      "opts.proto",
}

var E_MyFieldOption = &proto1.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*float32)(nil),
	Field:         50002,
	Name:          "mypb.my_field_option",
	Tag:           "fixed32,50002,opt,name=my_field_option,json=myFieldOption",
	Filename:      "opts.proto",
}

var E_MyEnumOption = &proto1.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50003,
	Name:          "mypb.my_enum_option",
	Tag:           "varint,50003,opt,name=my_enum_option,json=myEnumOption",
	Filename:      "opts.proto",
}

var E_MyEnumValueOption = &proto1.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*uint32)(nil),
	Field:         50004,
	Name:          "mypb.my_enum_value_option",
	Tag:           "varint,50004,opt,name=my_enum_value_option,json=myEnumValueOption",
	Filename:      "opts.proto",
}

var E_MyServiceOption = &proto1.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*MyEnum)(nil),
	Field:         50005,
	Name:          "mypb.my_service_option",
	Tag:           "varint,50005,opt,name=my_service_option,json=myServiceOption,enum=mypb.MyEnum",
	Filename:      "opts.proto",
}

var E_MyMethodOption = &proto1.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*MyMessage)(nil),
	Field:         50006,
	Name:          "mypb.my_method_option",
	Tag:           "bytes,50006,opt,name=my_method_option,json=myMethodOption",
	Filename:      "opts.proto",
}

func init() {
	proto1.RegisterType((*MyMessage)(nil), "mypb.MyMessage")
	proto1.RegisterType((*RequestType)(nil), "mypb.RequestType")
	proto1.RegisterType((*ResponseType)(nil), "mypb.ResponseType")
	proto1.RegisterEnum("mypb.MyEnum", MyEnum_name, MyEnum_value)
	proto1.RegisterExtension(E_MyFileOption)
	proto1.RegisterExtension(E_MyMessageOption)
	proto1.RegisterExtension(E_MyFieldOption)
	proto1.RegisterExtension(E_MyEnumOption)
	proto1.RegisterExtension(E_MyEnumValueOption)
	proto1.RegisterExtension(E_MyServiceOption)
	proto1.RegisterExtension(E_MyMethodOption)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyService service

type MyServiceClient interface {
	MyMethod(ctx context.Context, in *RequestType, opts ...grpc.CallOption) (*ResponseType, error)
}

type myServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyServiceClient(cc *grpc.ClientConn) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) MyMethod(ctx context.Context, in *RequestType, opts ...grpc.CallOption) (*ResponseType, error) {
	out := new(ResponseType)
	err := grpc.Invoke(ctx, "/mypb.MyService/MyMethod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyService service

type MyServiceServer interface {
	MyMethod(context.Context, *RequestType) (*ResponseType, error)
}

func RegisterMyServiceServer(s *grpc.Server, srv MyServiceServer) {
	s.RegisterService(&_MyService_serviceDesc, srv)
}

func _MyService_MyMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).MyMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mypb.MyService/MyMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).MyMethod(ctx, req.(*RequestType))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mypb.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MyMethod",
			Handler:    _MyService_MyMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opts.proto",
}

func init() { proto1.RegisterFile("opts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcd, 0x8b, 0xd3, 0x40,
	0x18, 0xc6, 0x37, 0x4d, 0xeb, 0xb6, 0xd3, 0xef, 0xc1, 0xc3, 0x18, 0xfc, 0xc8, 0xd6, 0x83, 0x8b,
	0x87, 0x14, 0x0a, 0x5e, 0x72, 0x51, 0x8b, 0xae, 0x82, 0x94, 0x42, 0x76, 0xf1, 0xe0, 0x82, 0xa5,
	0x69, 0xa6, 0xd9, 0xc0, 0x4c, 0x26, 0x66, 0x92, 0x95, 0x5c, 0x3d, 0x88, 0x47, 0x2f, 0x82, 0x47,
	0x8f, 0x9e, 0x17, 0x82, 0x67, 0xff, 0x03, 0x5d, 0x3f, 0xfe, 0x1e, 0x99, 0x99, 0xce, 0xb6, 0x8b,
	0xdd, 0x5b, 0xfb, 0xbe, 0x2f, 0xbf, 0xf7, 0x7d, 0x9e, 0x67, 0x02, 0x00, 0x4b, 0x32, 0xee, 0x24,
	0x29, 0xcb, 0x18, 0xac, 0xd2, 0x22, 0xf1, 0x2d, 0x3b, 0x64, 0x2c, 0x24, 0x78, 0x28, 0x6b, 0x7e,
	0xbe, 0x1c, 0x06, 0x98, 0x2f, 0xd2, 0x28, 0xc9, 0x58, 0xaa, 0xe6, 0x06, 0x0f, 0x41, 0x63, 0x52,
	0x4c, 0x30, 0xe7, 0xf3, 0x10, 0xc3, 0x1b, 0xc0, 0x5c, 0x32, 0x86, 0x0c, 0xdb, 0xd8, 0xaf, 0x8d,
	0x77, 0x3f, 0x95, 0x68, 0x67, 0xe7, 0xe3, 0x23, 0x4f, 0xd4, 0x60, 0x0f, 0x98, 0xfe, 0x3c, 0x45,
	0x15, 0xdb, 0xd8, 0x6f, 0x78, 0xe2, 0xa7, 0x5b, 0xfb, 0x50, 0xa2, 0xf3, 0xc6, 0xa0, 0x0d, 0x9a,
	0x1e, 0x7e, 0x93, 0x63, 0x9e, 0x1d, 0x15, 0x09, 0x1e, 0x74, 0x40, 0xcb, 0xc3, 0x3c, 0x61, 0x31,
	0xc7, 0xe2, 0xff, 0xfd, 0x7b, 0xe0, 0xda, 0xa4, 0x78, 0x1a, 0xe7, 0x14, 0x76, 0x80, 0x79, 0x30,
	0x9d, 0xf6, 0x0c, 0xab, 0xf6, 0xa5, 0x44, 0xdf, 0x2b, 0x70, 0x17, 0x98, 0xe3, 0xc7, 0x5e, 0xaf,
	0x62, 0x55, 0x3f, 0x97, 0xc8, 0x18, 0xbd, 0x16, 0x87, 0x1c, 0xe2, 0xf4, 0x34, 0x5a, 0x60, 0xf8,
	0x02, 0xd4, 0xc5, 0x55, 0xd9, 0x09, 0x0b, 0x60, 0xdf, 0x11, 0x52, 0x9c, 0x8d, 0x25, 0x16, 0xd4,
	0xa5, 0xf5, 0xa2, 0x01, 0x3a, 0x2b, 0x91, 0x59, 0xff, 0x56, 0x3d, 0x2b, 0x51, 0x1b, 0x36, 0x0f,
	0x19, 0xc5, 0x36, 0xcf, 0xd2, 0x28, 0x0e, 0xad, 0xea, 0xd7, 0x12, 0x19, 0xee, 0x13, 0xd0, 0xa1,
	0xc5, 0x6c, 0x19, 0x11, 0x3c, 0x63, 0x49, 0x16, 0xb1, 0x18, 0xde, 0x74, 0x94, 0x3b, 0x8e, 0x76,
	0xc7, 0x39, 0x88, 0x08, 0x9e, 0xca, 0x26, 0x47, 0x3f, 0xde, 0x9b, 0x52, 0x6b, 0x8b, 0x16, 0xeb,
	0xb2, 0x3b, 0x01, 0x7d, 0x5a, 0xcc, 0xa8, 0xf2, 0x4b, 0x83, 0xee, 0xfc, 0x07, 0x5a, 0x19, 0xaa,
	0x59, 0x3f, 0x25, 0xab, 0xe6, 0x75, 0x69, 0x71, 0xa9, 0xe3, 0x3e, 0x03, 0x5d, 0x79, 0x14, 0x26,
	0x81, 0x86, 0xdd, 0xda, 0x72, 0x15, 0x26, 0x81, 0x46, 0x9d, 0x4b, 0x54, 0xc5, 0x6b, 0x8b, 0xb3,
	0x2e, 0xea, 0x2b, 0x75, 0x38, 0xce, 0xe9, 0xd5, 0xea, 0x44, 0x0a, 0x1a, 0xf3, 0x4b, 0x62, 0xea,
	0x42, 0xdd, 0xba, 0xec, 0x1e, 0x81, 0xeb, 0x9a, 0x72, 0x3a, 0x27, 0xf9, 0x85, 0xc0, 0xbd, 0xad,
	0xac, 0x97, 0x62, 0x44, 0x03, 0x7f, 0x4b, 0x60, 0xdb, 0xeb, 0x2b, 0xe0, 0x46, 0xcf, 0x3d, 0x96,
	0x9e, 0x71, 0x15, 0xed, 0xd5, 0x9e, 0xad, 0xb2, 0xd7, 0xc0, 0x3f, 0x12, 0xd8, 0x19, 0xb5, 0x54,
	0xd6, 0xea, 0x11, 0x09, 0x07, 0x2f, 0xcd, 0xb9, 0xc7, 0xa0, 0x27, 0x03, 0x11, 0x4f, 0x45, 0xb3,
	0x6f, 0x6f, 0xc9, 0x43, 0xf4, 0x35, 0xfa, 0xaf, 0x44, 0x37, 0x47, 0x5d, 0x8d, 0x5e, 0x85, 0xe2,
	0x75, 0x68, 0xb1, 0x39, 0x39, 0x7e, 0xf0, 0xae, 0x44, 0xad, 0xe7, 0x98, 0x10, 0x66, 0xbf, 0x65,
	0x29, 0x09, 0xf6, 0x5e, 0xdd, 0x0d, 0xa3, 0xec, 0x24, 0xf7, 0x9d, 0x05, 0xa3, 0xc3, 0x3c, 0x09,
	0x58, 0x48, 0xa2, 0x7c, 0x98, 0xf8, 0x6a, 0x31, 0x57, 0xdf, 0xd9, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc5, 0x32, 0x3f, 0x74, 0x88, 0x03, 0x00, 0x00,
}
